PLUGIN_NAME=			controld-guru
PLUGIN_VERSION=		1.3
PLUGIN_REVISION=	9_1
PLUGIN_COMMENT=		ControlD DNS plugin for OPNsense 25.1
PLUGIN_MAINTAINER=	opnsense@gurupannu.com

.include "../../Mk/plugins.mk"
