PLUGIN_NAME=			controld-guru
PLUGIN_VERSION=		26.1
PLUGIN_REVISION=	0.3
PLUGIN_COMMENT=		ControlD DNS plugin for OPNsense 26.1
PLUGIN_MAINTAINER=	opnsense@gurupannu.com

.include "../../Mk/plugins.mk"
