PLUGIN_NAME=		telegram-guru
PLUGIN_VERSION=		26.1
PLUGIN_REVISION=  0.1
PLUGIN_COMMENT=   Monit Alerts to Telegram plugin for OPNsense 26.1
PLUGIN_MAINTAINER=  opnsense@gurupannu.com
#PLUGIN_DEPENDS=

.include "../../Mk/plugins.mk"
