PLUGIN_NAME=			nextdns-guru
PLUGIN_VERSION=		26.1
PLUGIN_REVISION=  0.1
PLUGIN_COMMENT=		NextDNS DNS plugin for OPNsense 26.1
PLUGIN_MAINTAINER=	opnsense@gurupannu.com

.include "../../Mk/plugins.mk"
