PLUGIN_NAME=			adguardhome-guru
PLUGIN_VERSION=		26.1
PLUGIN_REVISION=  0.2
PLUGIN_COMMENT=		AdGuardHome DNS plugin for OPNsense v26.1
PLUGIN_MAINTAINER=	opnsense@gurupannu.com

.include "../../Mk/plugins.mk"
