PLUGIN_NAME=			adguardhome-guru
PLUGIN_VERSION=		1.5
PLUGIN_REVISION=  0.0
PLUGIN_COMMENT=		AdGuardHome DNS plugin for OPNsense v25.1
PLUGIN_MAINTAINER=	opnsense@gurupannu.com

.include "../../Mk/plugins.mk"
